// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/fire_service.proto
#ifndef GRPC_proto_2ffire_5fservice_2eproto__INCLUDED
#define GRPC_proto_2ffire_5fservice_2eproto__INCLUDED

#include "proto/fire_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace fire_service {

// Service definition
class FireQueryService final {
 public:
  static constexpr char const* service_full_name() {
    return "fire_service.FireQueryService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Client -> Gateway (Process A): Submit a query
    std::unique_ptr< ::grpc::ClientReaderInterface< ::fire_service::QueryResponseChunk>> Query(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::fire_service::QueryResponseChunk>>(QueryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::fire_service::QueryResponseChunk>> AsyncQuery(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::fire_service::QueryResponseChunk>>(AsyncQueryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::fire_service::QueryResponseChunk>> PrepareAsyncQuery(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::fire_service::QueryResponseChunk>>(PrepareAsyncQueryRaw(context, request, cq));
    }
    // Client -> Gateway: Cancel a request
    virtual ::grpc::Status CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::fire_service::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>> AsyncCancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>>(AsyncCancelRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>> PrepareAsyncCancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>>(PrepareAsyncCancelRequestRaw(context, request, cq));
    }
    // Client -> Gateway: Check request status
    virtual ::grpc::Status GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::fire_service::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>> AsyncGetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>>(AsyncGetStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    // Internal: Process to Process communication
    virtual ::grpc::Status InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::fire_service::InternalQueryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::InternalQueryResponse>> AsyncInternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::InternalQueryResponse>>(AsyncInternalQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::InternalQueryResponse>> PrepareAsyncInternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::InternalQueryResponse>>(PrepareAsyncInternalQueryRaw(context, request, cq));
    }
    // Internal: One-way notification (optional)
    virtual ::grpc::Status Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::fire_service::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>> AsyncNotify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>>(AsyncNotifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>> PrepareAsyncNotify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>>(PrepareAsyncNotifyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Client -> Gateway (Process A): Submit a query
      virtual void Query(::grpc::ClientContext* context, const ::fire_service::QueryRequest* request, ::grpc::ClientReadReactor< ::fire_service::QueryResponseChunk>* reactor) = 0;
      // Client -> Gateway: Cancel a request
      virtual void CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Client -> Gateway: Check request status
      virtual void GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Internal: Process to Process communication
      virtual void InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Internal: One-way notification (optional)
      virtual void Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::fire_service::QueryResponseChunk>* QueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::fire_service::QueryResponseChunk>* AsyncQueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::fire_service::QueryResponseChunk>* PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>* AsyncCancelRequestRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>* PrepareAsyncCancelRequestRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::InternalQueryResponse>* AsyncInternalQueryRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::InternalQueryResponse>* PrepareAsyncInternalQueryRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>* AsyncNotifyRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fire_service::StatusResponse>* PrepareAsyncNotifyRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::fire_service::QueryResponseChunk>> Query(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::fire_service::QueryResponseChunk>>(QueryRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>> AsyncQuery(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>>(AsyncQueryRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>> PrepareAsyncQuery(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>>(PrepareAsyncQueryRaw(context, request, cq));
    }
    ::grpc::Status CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::fire_service::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>> AsyncCancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>>(AsyncCancelRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>> PrepareAsyncCancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>>(PrepareAsyncCancelRequestRaw(context, request, cq));
    }
    ::grpc::Status GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::fire_service::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>> AsyncGetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>>(AsyncGetStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    ::grpc::Status InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::fire_service::InternalQueryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>> AsyncInternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>>(AsyncInternalQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>> PrepareAsyncInternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>>(PrepareAsyncInternalQueryRaw(context, request, cq));
    }
    ::grpc::Status Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::fire_service::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>> AsyncNotify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>>(AsyncNotifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>> PrepareAsyncNotify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>>(PrepareAsyncNotifyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Query(::grpc::ClientContext* context, const ::fire_service::QueryRequest* request, ::grpc::ClientReadReactor< ::fire_service::QueryResponseChunk>* reactor) override;
      void CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response, std::function<void(::grpc::Status)>) override;
      void InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::fire_service::QueryResponseChunk>* QueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request) override;
    ::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>* AsyncQueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>* PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* AsyncCancelRequestRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* PrepareAsyncCancelRequestRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>* AsyncInternalQueryRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>* PrepareAsyncInternalQueryRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* AsyncNotifyRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* PrepareAsyncNotifyRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Query_;
    const ::grpc::internal::RpcMethod rpcmethod_CancelRequest_;
    const ::grpc::internal::RpcMethod rpcmethod_GetStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_InternalQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_Notify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Client -> Gateway (Process A): Submit a query
    virtual ::grpc::Status Query(::grpc::ServerContext* context, const ::fire_service::QueryRequest* request, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* writer);
    // Client -> Gateway: Cancel a request
    virtual ::grpc::Status CancelRequest(::grpc::ServerContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response);
    // Client -> Gateway: Check request status
    virtual ::grpc::Status GetStatus(::grpc::ServerContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response);
    // Internal: Process to Process communication
    virtual ::grpc::Status InternalQuery(::grpc::ServerContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response);
    // Internal: One-way notification (optional)
    virtual ::grpc::Status Notify(::grpc::ServerContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Query() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::fire_service::QueryRequest* /*request*/, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuery(::grpc::ServerContext* context, ::fire_service::QueryRequest* request, ::grpc::ServerAsyncWriter< ::fire_service::QueryResponseChunk>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CancelRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CancelRequest() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CancelRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRequest(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelRequest(::grpc::ServerContext* context, ::fire_service::StatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::fire_service::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStatus() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::fire_service::StatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::fire_service::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InternalQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InternalQuery() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_InternalQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InternalQuery(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::InternalQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInternalQuery(::grpc::ServerContext* context, ::fire_service::InternalQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::fire_service::InternalQueryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Notify() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Notify(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotify(::grpc::ServerContext* context, ::fire_service::InternalQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::fire_service::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Query<WithAsyncMethod_CancelRequest<WithAsyncMethod_GetStatus<WithAsyncMethod_InternalQuery<WithAsyncMethod_Notify<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Query() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::fire_service::QueryRequest, ::fire_service::QueryResponseChunk>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fire_service::QueryRequest* request) { return this->Query(context, request); }));
    }
    ~WithCallbackMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::fire_service::QueryRequest* /*request*/, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::fire_service::QueryResponseChunk>* Query(
      ::grpc::CallbackServerContext* /*context*/, const ::fire_service::QueryRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CancelRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CancelRequest() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::fire_service::StatusRequest, ::fire_service::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response) { return this->CancelRequest(context, request, response); }));}
    void SetMessageAllocatorFor_CancelRequest(
        ::grpc::MessageAllocator< ::fire_service::StatusRequest, ::fire_service::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fire_service::StatusRequest, ::fire_service::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CancelRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRequest(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetStatus() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::fire_service::StatusRequest, ::fire_service::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response) { return this->GetStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetStatus(
        ::grpc::MessageAllocator< ::fire_service::StatusRequest, ::fire_service::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fire_service::StatusRequest, ::fire_service::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InternalQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InternalQuery() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response) { return this->InternalQuery(context, request, response); }));}
    void SetMessageAllocatorFor_InternalQuery(
        ::grpc::MessageAllocator< ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InternalQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InternalQuery(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::InternalQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InternalQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::InternalQueryResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Notify() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response) { return this->Notify(context, request, response); }));}
    void SetMessageAllocatorFor_Notify(
        ::grpc::MessageAllocator< ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Notify(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Notify(
      ::grpc::CallbackServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::StatusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Query<WithCallbackMethod_CancelRequest<WithCallbackMethod_GetStatus<WithCallbackMethod_InternalQuery<WithCallbackMethod_Notify<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Query() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::fire_service::QueryRequest* /*request*/, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CancelRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CancelRequest() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CancelRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRequest(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStatus() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InternalQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InternalQuery() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_InternalQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InternalQuery(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::InternalQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Notify() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Notify(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Query() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::fire_service::QueryRequest* /*request*/, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CancelRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CancelRequest() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CancelRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRequest(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStatus() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InternalQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InternalQuery() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_InternalQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InternalQuery(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::InternalQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInternalQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Notify() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Notify(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotify(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Query() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Query(context, request); }));
    }
    ~WithRawCallbackMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::fire_service::QueryRequest* /*request*/, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Query(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CancelRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CancelRequest() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CancelRequest(context, request, response); }));
    }
    ~WithRawCallbackMethod_CancelRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelRequest(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetStatus() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InternalQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InternalQuery() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InternalQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_InternalQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InternalQuery(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::InternalQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InternalQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Notify() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Notify(context, request, response); }));
    }
    ~WithRawCallbackMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Notify(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Notify(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CancelRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CancelRequest() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fire_service::StatusRequest, ::fire_service::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fire_service::StatusRequest, ::fire_service::StatusResponse>* streamer) {
                       return this->StreamedCancelRequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CancelRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CancelRequest(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancelRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fire_service::StatusRequest,::fire_service::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetStatus() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fire_service::StatusRequest, ::fire_service::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fire_service::StatusRequest, ::fire_service::StatusResponse>* streamer) {
                       return this->StreamedGetStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::fire_service::StatusRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fire_service::StatusRequest,::fire_service::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InternalQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InternalQuery() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse>* streamer) {
                       return this->StreamedInternalQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InternalQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InternalQuery(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::InternalQueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInternalQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fire_service::InternalQueryRequest,::fire_service::InternalQueryResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Notify() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse>* streamer) {
                       return this->StreamedNotify(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Notify(::grpc::ServerContext* /*context*/, const ::fire_service::InternalQueryRequest* /*request*/, ::fire_service::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNotify(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fire_service::InternalQueryRequest,::fire_service::StatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CancelRequest<WithStreamedUnaryMethod_GetStatus<WithStreamedUnaryMethod_InternalQuery<WithStreamedUnaryMethod_Notify<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Query() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::fire_service::QueryRequest, ::fire_service::QueryResponseChunk>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::fire_service::QueryRequest, ::fire_service::QueryResponseChunk>* streamer) {
                       return this->StreamedQuery(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::fire_service::QueryRequest* /*request*/, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedQuery(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::fire_service::QueryRequest,::fire_service::QueryResponseChunk>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Query<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Query<WithStreamedUnaryMethod_CancelRequest<WithStreamedUnaryMethod_GetStatus<WithStreamedUnaryMethod_InternalQuery<WithStreamedUnaryMethod_Notify<Service > > > > > StreamedService;
};

}  // namespace fire_service


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_proto_2ffire_5fservice_2eproto__INCLUDED
