// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/fire_service.proto

#include "proto/fire_service.pb.h"
#include "proto/fire_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace fire_service {

static const char* FireQueryService_method_names[] = {
  "/fire_service.FireQueryService/Query",
  "/fire_service.FireQueryService/CancelRequest",
  "/fire_service.FireQueryService/GetStatus",
  "/fire_service.FireQueryService/InternalQuery",
  "/fire_service.FireQueryService/Notify",
};

std::unique_ptr< FireQueryService::Stub> FireQueryService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FireQueryService::Stub> stub(new FireQueryService::Stub(channel, options));
  return stub;
}

FireQueryService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Query_(FireQueryService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_CancelRequest_(FireQueryService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStatus_(FireQueryService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InternalQuery_(FireQueryService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Notify_(FireQueryService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::fire_service::QueryResponseChunk>* FireQueryService::Stub::QueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::fire_service::QueryResponseChunk>::Create(channel_.get(), rpcmethod_Query_, context, request);
}

void FireQueryService::Stub::async::Query(::grpc::ClientContext* context, const ::fire_service::QueryRequest* request, ::grpc::ClientReadReactor< ::fire_service::QueryResponseChunk>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::fire_service::QueryResponseChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>* FireQueryService::Stub::AsyncQueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::fire_service::QueryResponseChunk>::Create(channel_.get(), cq, rpcmethod_Query_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::fire_service::QueryResponseChunk>* FireQueryService::Stub::PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::fire_service::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::fire_service::QueryResponseChunk>::Create(channel_.get(), cq, rpcmethod_Query_, context, request, false, nullptr);
}

::grpc::Status FireQueryService::Stub::CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::fire_service::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fire_service::StatusRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelRequest_, context, request, response);
}

void FireQueryService::Stub::async::CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fire_service::StatusRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelRequest_, context, request, response, std::move(f));
}

void FireQueryService::Stub::async::CancelRequest(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* FireQueryService::Stub::PrepareAsyncCancelRequestRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fire_service::StatusResponse, ::fire_service::StatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* FireQueryService::Stub::AsyncCancelRequestRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FireQueryService::Stub::GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::fire_service::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fire_service::StatusRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStatus_, context, request, response);
}

void FireQueryService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fire_service::StatusRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, std::move(f));
}

void FireQueryService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* FireQueryService::Stub::PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fire_service::StatusResponse, ::fire_service::StatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* FireQueryService::Stub::AsyncGetStatusRaw(::grpc::ClientContext* context, const ::fire_service::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FireQueryService::Stub::InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::fire_service::InternalQueryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InternalQuery_, context, request, response);
}

void FireQueryService::Stub::async::InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InternalQuery_, context, request, response, std::move(f));
}

void FireQueryService::Stub::async::InternalQuery(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InternalQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>* FireQueryService::Stub::PrepareAsyncInternalQueryRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fire_service::InternalQueryResponse, ::fire_service::InternalQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InternalQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fire_service::InternalQueryResponse>* FireQueryService::Stub::AsyncInternalQueryRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInternalQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FireQueryService::Stub::Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::fire_service::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Notify_, context, request, response);
}

void FireQueryService::Stub::async::Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Notify_, context, request, response, std::move(f));
}

void FireQueryService::Stub::async::Notify(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Notify_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* FireQueryService::Stub::PrepareAsyncNotifyRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fire_service::StatusResponse, ::fire_service::InternalQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Notify_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fire_service::StatusResponse>* FireQueryService::Stub::AsyncNotifyRaw(::grpc::ClientContext* context, const ::fire_service::InternalQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNotifyRaw(context, request, cq);
  result->StartCall();
  return result;
}

FireQueryService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FireQueryService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FireQueryService::Service, ::fire_service::QueryRequest, ::fire_service::QueryResponseChunk>(
          [](FireQueryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fire_service::QueryRequest* req,
             ::grpc::ServerWriter<::fire_service::QueryResponseChunk>* writer) {
               return service->Query(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FireQueryService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FireQueryService::Service, ::fire_service::StatusRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FireQueryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fire_service::StatusRequest* req,
             ::fire_service::StatusResponse* resp) {
               return service->CancelRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FireQueryService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FireQueryService::Service, ::fire_service::StatusRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FireQueryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fire_service::StatusRequest* req,
             ::fire_service::StatusResponse* resp) {
               return service->GetStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FireQueryService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FireQueryService::Service, ::fire_service::InternalQueryRequest, ::fire_service::InternalQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FireQueryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fire_service::InternalQueryRequest* req,
             ::fire_service::InternalQueryResponse* resp) {
               return service->InternalQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FireQueryService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FireQueryService::Service, ::fire_service::InternalQueryRequest, ::fire_service::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FireQueryService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fire_service::InternalQueryRequest* req,
             ::fire_service::StatusResponse* resp) {
               return service->Notify(ctx, req, resp);
             }, this)));
}

FireQueryService::Service::~Service() {
}

::grpc::Status FireQueryService::Service::Query(::grpc::ServerContext* context, const ::fire_service::QueryRequest* request, ::grpc::ServerWriter< ::fire_service::QueryResponseChunk>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FireQueryService::Service::CancelRequest(::grpc::ServerContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FireQueryService::Service::GetStatus(::grpc::ServerContext* context, const ::fire_service::StatusRequest* request, ::fire_service::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FireQueryService::Service::InternalQuery(::grpc::ServerContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::InternalQueryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FireQueryService::Service::Notify(::grpc::ServerContext* context, const ::fire_service::InternalQueryRequest* request, ::fire_service::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fire_service
#include <grpcpp/ports_undef.inc>

